#!groovy

// Generated by IBM TransformationAdvisor
// Tue Oct 02 14:56:22 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'jpetstorewar'
    mvnCommands = '--version'
    test='false'
}