#!groovy

// Generated by IBM TransformationAdvisor
// Mon Sep 24 16:54:10 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}