#!groovy

// Generated by IBM TransformationAdvisor
// Thu Sep 13 12:25:58 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'jpetstorewar'
    mvnCommands = '--version'
    test='false'
}